### ISSUE TITLE
Problems when I create reminder

### ISSUE THREAD

**Issue by trantuananh1** [gophertuts/reminders-cli#2]
I am very thankful about this project. I cloned, installed and run successfully. But it has some problems:
1. When I created reminder, the field "id" in JSON output doesn't have value
2. I created reminder, then I go into db.json to find id of recent reminder and use "fetch" command, it return null
3. I think notification only notify once, but it repeats many times, I don't know

Please help me solve these problems.

**Comment by steevehook** [comment]
> I am very thankful about this project. I cloned, installed and run successfully. But it has some problems:
> 
> 1. When I created reminder, the field "id" in JSON output doesn't have value
> 2. I created reminder, then I go into db.json to find id of recent reminder and use "fetch" command, it return null
> 3. I think notification only notify once, but it repeats many times, I don't know
> 
> Please help me solve these problems.

Hi @tta9799zzs could you please share an archive of the exact code you're running so I could have a look into it?
Glad you're enjoying it.

Also considering asking questions in the Discord server:

https://discord.gg/tprewQu

**Comment by trantuananh1** [comment]
I forked your project here:
https://github.com/tta9799zzs/reminders-cli
And these are some screenshots when using create and fetch command:
https://drive.google.com/drive/folders/1PIih-y3RPZj1DHW87yuXrXSRpw46Tvn0

**Comment by steevehook** [comment]
Yeah. I recently tested everything. It seems the server works perfectly. I must've messed the HTTP client in the command switch while creating the tutorials and now it display incorrect info, although the server responds correctly. Here's the [commit](https://github.com/gophertuts/reminders-cli/commit/88592c913782aa54263fb5885b1a2c64233196b9) which fixes it:

Huge thanks for the contribution @tta9799zzs , really appreciate it
